// deno-coverage-ignore-file -- type declarations only: erased at compile time, so no
// test can ever load this module at runtime.

export type Keyword =
  | "program"
  | "procedure"
  | "function"
  | "class"
  | "def"
  | "begin"
  | "end"
  | "endproc"
  | "if"
  | "then"
  | "else"
  | "elif"
  | "endif"
  | "for"
  | "to"
  | "downto"
  | "step"
  | "in"
  | "next"
  | "while"
  | "endwhile"
  | "do"
  | "repeat"
  | "until"
  | "pass"
  | "return"
  | "break"
  | "continue"
  | "const"
  | "final"
  | "var"
  | "dim"
  | "local"
  | "private"
  | "global"
  | "nonlocal"
  | "array"
  | "of"
  | "void"
  | "boolean"
  | "character"
  | "integer"
  | "string";

export type Type = "boolint" | "boolean" | "integer" | "character" | "string";

export type Operator =
  | "neg"
  | "not"
  | "plus"
  | "subt"
  | "mult"
  | "divr"
  | "div"
  | "mod"
  | "and"
  | "or"
  | "xor"
  | "andl"
  | "orl"
  | "scat"
  | "eqal"
  | "noeq"
  | "less"
  | "more"
  | "lseq"
  | "mreq"
  | "seql"
  | "sneq"
  | "sles"
  | "smor"
  | "sleq"
  | "smeq"
  | "lmul" // Python list multiplication ("[x]*n") - never a lexeme subtype, only synthesized by the parser
  | "smul" // Python string repetition, likewise synthesized only
  // Python membership tests, synthesized only (the source spells them with the
  // "in" keyword). "l" = against a list, "s" = substring; "n" = negated.
  | "lin"
  | "lnin"
  | "sin"
  | "snin";

export type Delimiter =
  | "("
  | ")"
  | "{"
  | "}"
  | "["
  | "]"
  | ","
  | ":"
  | ";"
  | "."
  | ".."
  | "->";
